#!/usr/bin/env bash
definitions=/usr/local/lib/solidgroundux/globals/solidgrond-management-modules-definitions.sh
[[ -r "$definitions" ]] || exit 0
# shellcheck source=/dev/null
source "$definitions"
printf '%s %s.%s\n' "$SGND_SOLIDGROND_MANAGEMENT_MODULES_PRODUCT" "$SGND_SOLIDGROND_MANAGEMENT_MODULES_VERSION" "$SGND_SOLIDGROND_MANAGEMENT_MODULES_BUILD"
